markdown: kramdown
timezone: Europe/Rome
title: Riccardo Bruno home page
email: riccardo.bruno@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Riccardo Bruno home page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ricsxn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: ricsxn
github_username: ricsxn
theme: minima
#theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
logo: images/me.png
show_downloads: [false]
google_analytics: "UA-148332475-1"
future: true
